/*
*******Access Modifier*********
-> You have 4 kind of access modifiers. Private, Protected, Public and Global. From most restrictive to less restrictive.

*Private*
-> Default access modifier, can be used with variables, methods and innerclasses. But you cannot declare main class as private.
-> Restrict access within outer class scope.
-> If you don't define any modifier, by default the access modifier is private.
-> If you declare private varilable or methods, this cannot be accessed by innerclasses too.


*Protected*
-> Can be used with variables and methods.
-> Inner classes and classes that extends outer class can access these variables and methods.

*Public*
-> Can be used with classes, variables and methods.
-> Unrestricted access within same namespace.

*Global*
-> It's unrestricted, variables, methods and classes are accessible by everyone. 
-> Even these are accessible outside the namespace.

*/