/*
***********OOPS*********
-> Stands for object oriented programming system

**Object**
-> It's a real world entity, like a student, a dog, car, country etc. Anything you see in real world is an object.
-> An object has properties like name, age, rollnumber and behaviour markAttendece(), payFees(), getMarks().
-> The properties and behaviour give a defination for an object.
-> Most of programming languages use class as an object or give defination to an object. Where properties called varilable and behaviour called methods/functions.

**OOPS Pillars**
-> The 4 main pillars of OOPS are -
Encapsulation - Bundling the code.
Abstraction - Which is hiding the code
Inheritance - Designing the code layout
Polymorphism - Getting multiple definations

*/