/*
************Expressions And Operators************
-> Any single line statement, that gives us a value is called an expression.

*/

// = is assignment operator and right handside statment is experssion
DateTime currentDateTime = DateTime.newInstance(2024, 8, 5, 12, 12, 0);
List<Integer> rollnumbers = new List<Integer> {11008890, 11008100, 11007231};


// assignment operator
Integer x = 5;
System.debug(x);

// addition operator
x = x + 5;
System.debug(x);

// subtraction operator
x = x -5;
System.debug(x);

// mulitplication operator
x = x * 5;
System.debug(x);

// division operator
x = x/5;
System.debug(x);