
// String data type
String greeting = 'Hello World';
System.debug(greeting);

// Boolean data type
Boolean amIwake = true;
System.debug(amIwake);

// Integer data type
Integer rollNumber = 11223350;
System.debug(rollNumber);

// Long data type
Long worldPopulation = 7000000000L;
System.debug(worldPopulation);

// Double data type
Double lightSpeed = 93000000/186000;
System.debug(lightSpeed);

//Date data type
Date tDay = Date.newInstance(2024, 20, 07);
System.debug(tDay);

//Time data type
Time currentTime = Time.newInstance(3, 25, 0, 0);
System.debug(currentTime);

//DateTime data type
DateTime currentDateTime = DateTime.newInstance(2024, 20, 07, 3, 25, 0);
System.debug(currentDateTime);
